print("Start")
print("  |")
print("  v")
print("Locate the Start Oval")
print("  |")
print("  v")
print("Follow the arrow to the next shape")
print("  |")
print("  v")
print("What shape is it?")
print("      /              \\")
print(" [Rectangle]      [Diamond]")
print("      |               |")
print("      v               v")
print("Read the action/   Read the question and")
print("   statement       choose path that is true")
print("      \\               /")
print("       \\____     ____/")
print("            |   |")
print("            v   v")
print("  Follow arrow to next shape")
print("            |")
print("            v")
print("    Is the shape an Oval?")
print("      /             \\")
print("     No             Yes ----> [End]")
print("      |")
print("      ^-----------------------|")
print("      (Returns to 'What shape is it?')")