print("Start")
print("  |")
print("  v")
print("+----------------------+")
print("| Follow Liberty Avenue | <----+")
print("+----------------------+      |")
print("  |                           |")
print("  v                           |")
print("Reached 2 Miles? -------------+ No")
print("  |")
print("  | Yes")
print("  v")
print("+----------------------+")
print("| Left Turn onto 40th St|")
print("+----------------------+")
print("  |")
print("  v")
print("+----------------------+")
print("| Drive toward Bridge  | <----+")
print("+----------------------+      |")
print("  |                           |")
print("  v                           |")
print("Reached the Bridge? ----------+ No")
print("  |")
print("  | Yes")
print("  v")
print("+----------------------+")
print("| Right Turn onto Foster|")
print("+----------------------+")
print("  |")
print("  v")
print("+----------------------+")
print("| Take First Left Turn  |")
print("+----------------------+")
print("  |")
print("  v")
print("+----------------------+")
print("| Follow Road          | <----+")
print("+----------------------+      |")
print("  |                           |")
print("  v                           |")
print("At NREC Building? ------------+ No")
print("  |")
print("  | Yes")
print("  v")
print(" End")