
print("        Start")
print("          |")
print("          v")
print("   +---------------+ ")
print("   | Approach Curb |")
print("   +---------------+ ")
print("          |")
print("          v")
print("   +---------------+ <----------+")
print("   |   Look Left   |            |")
print("   +---------------+            |")
print("          |                     |")
print("          v                     |")
print("   +---------------+            |")
print("   |   Look Right  |            |")
print("   +---------------+            |")
print("          |                     |")
print("          v                     |")
print("       /     \\                  |")
print("      /Is there\\                 |")
print("     < oncoming  >               |")
print("      \\ traffic?/                |")
print("       \\       /                 |")
print("        /     \\                  |")
print("   Yes /       \\ No              |")
print("      v         v                |")
print("+----------+  +--------------+   |")
print("| Wait for |  |  Cross the   |   |")
print("| Cars to  |  |    Street    |   |")
print("| Pass     |  +--------------+   |")
print("+----------+         |           |")
print("      |              v           |")
print("      |             End          |")
print("      +--------------------------+")