print("      Start")
print("        |")
print("        v")
print("  +-----------+")
print("  |Take a Pace|<-------+")
print("  +-----------+        |")
print("        |              |")
print("        v              |")
print("      /   \\            |")
print("     / Have \\          |")
print("    < 20 paces >-------+ No")
print("     \\ been  /")
print("      \\taken?/")
print("        |")
print("        | Yes")
print("        v")
print("    +-------+")
print("    | Turn  |")
print("    +-------+")
print("        |")
print("        v")
print("    +-------+")
print("    | Shoot |")
print("    +-------+")
print("        |")
print("        v")
print("       End")