print("       Start")
print("         |")
print("         v")
print("  +--------------+")
print("  | Turn on Oven |")
print("  +--------------+")
print("         |")
print("         v")
print("  +--------------+")
print("  | Cook Turkey  |<-----------+")
print("  +--------------+            |")
print("         |                    |")
print("         v                    |")
print("      /      \\                |")
print("     / 4 Hours \\               |")
print("    <  Elapsed  >--------------+ No")
print("     \\ OR Temp /")
print("      \\>= 180F?/")
print("         |")
print("         | Yes")
print("         v")
print("  +--------------+")
print("  | Turn off Oven|")
print("  +--------------+")
print("         |")
print("         v")
print("        End")